### PR TITLE
Merge 1.7.1 and backport fix for cuDF null handling

### PR DESCRIPTION
**Pull request by wphicks**

### CODE REVIEW

**Comment by wphicks** [comment]
rerun tests

**Comment by trivialfis** [comment]
It's probably a good idea to track 1.7 branch first.

**Comment by wphicks** [comment]
> It's probably a good idea to track 1.7 branch first.
Sorry, I don't quite follow what you mean?

**Review by AyodeAwe — APPROVED** [review]

**Comment by trivialfis** [comment]
Apologies for the ambiguity, I saw that the 22.12 branch is tracking the dmlc 1.6 branch, which is old.

**Pull request merged**
